name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # <-- required for GitHub Pages deploy

jobs:
  ci:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      # Only build on main branch
      - if: github.ref == 'refs/heads/main'
        run: npm run build
      # Only upload artifact on main branch
      - if: github.ref == 'refs/heads/main'
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  # CD only runs after successful main CI
  cd:
    name: Deploy to GitHub Pages
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
