name: CD Pipeline

# Trigger only after CI workflow succeeds
on:
  workflow_run:
    workflows: ["CI Pipeline"] # exact name of the CI workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # ✅ ensure CI passed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
