name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Download the artifact from CI if triggered by workflow_run
      - name: Download artifact
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      # If manual dispatch, build locally
      - name: Build (manual dispatch only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm ci
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: actions/deploy-pages@v1
