name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"] # triggers only after CI
    types:
      - completed
  workflow_dispatch: # optional manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only run if CI succeeded
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
